AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    CreateSlotLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: createSlot.handler
        Runtime: nodejs14.x
        Events:
          PostLambdaApi:
            Type: Api
            Properties:
              Path: /
              Method: post

    UpdateSlotLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: updateSlot.handler
        Runtime: nodejs14.x
        Events:
          PutLambdaApi:
            Type: Api
            Properties:
              Path: /
              Method: put

    GetLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: getSlots.handler
        Runtime: nodejs14.x
        Events:
          GetLambdaApi:
            Type: Api
            Properties:
              Path: /
              Method: get

Outputs:
  PostLambdaApi:
    Description: "API Gateway endpoint URL for GetLambdaFunction on dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  PostLambdaFunction:
    Description: "Post Lambda Function ARN"
    Value: !GetAtt PostLambdaFunction.Arn
